version = 0.1

[default.deploy.parameters]
stack_name = "bobalovers"
resolve_s3 = true
s3_prefix = "bobalovers"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
confirm_changeset = true

[default.global.parameters]
region = "us-west-2"
